server:
  port: 4000
spring:
  application:
    name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.107.255.115:6006/eureka/

#zuul:
#  routes:
#    user-service: /user/** #路由映射
#  ignored-services: user-service #取消代理

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: false

zuul:
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000