server:
  port: 4000
spring:
  application:
    name: gateway
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Lyt@2019
    url: jdbc:mysql://47.107.255.115:3306/hospital??useUnicode=true&characterEncoding=utf8&useSSL=false

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://47.107.255.115:6006/eureka/

#ribbon:
#  ReadTimeout: 12000
#  ConnectTimeout: 12000
#  eureka:
#    enabled: true
#zuul:
#  host:
#    socket-timeout-millis: 12000
#    connect-timeout-millis: 12000



zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    echo:
      path: /report-service/**
      serviceId: report-service


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000