server:
  port: 4000
spring:
  application:
    name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.107.255.115:6006/eureka/

#zuul:
#  routes:
#    user-service: /user/** #路由映射
#  ignored-services: user-service #取消代理