server:
  port: 4000
spring:
  application:
    name: gateway
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Lyt@2019
    url: jdbc:mysql://47.107.255.115:3306/hospital??useUnicode=true&characterEncoding=utf8&useSSL=false

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://47.107.255.115:6006/eureka/


#zuul:
#  routes:
#    user-service: /user/** #路由映射
#  ignored-services: user-service #取消代理

#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000
#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 1
#  eureka:
#    enabled: false

zuul:
  ribbon-isolation-strategy: thread
  max:
    host:
      connections: 5000
  host:
    socket-timeout-millis: 6000
    connect-timeout-millis: 6000