server:
  port: 6006
spring:
  application:
    name: registry

eureka:
  instance:
    hostname: eureka
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://47.107.255.115:6006/eureka/
  server:
    enable-self-preservation: true