server:
  port: 6006
spring:
  application:
    name: registry-service

eureka:
  instance:
    hostname: eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://47.107.255.115:6006/eureka/