pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                dir("user-service") {
                    sh "mvn -Dmaven.test.failure.ignore clean install"
                }
            }
        }
        stage('Image') {
            steps {
                sh "docker build -t user-service -f user-service/deploy/Dockerfile ."
            }
        }
    }
    post {
        success {
            script {
                echo "构建成功"
            }
        }

        failure {
            script {
                echo "构建失败"
            }
        }
    }
    options {
        //保持构建的最大个数
        buildDiscarder(logRotator( daysToKeepStr: '5',numToKeepStr: '5'));
    }
}