pipeline {
    agent any
    stages {
        stage('Build') {
            steps {

                    sh "mvn -Dmaven.test.failure.ignore clean install "
                
            }
        }
    }
    post {
        success {
            script {
                sh 'ls'
            }
        }

        failure {
            script {
                sh 'java -version'
            }
        }
    }
}