pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                dir("user-service") {
                    sh "mvn -Dmaven.test.failure.ignore clean install"
                }
            }
        }
        stage('Image') {
            steps {
                sh "docker build -t user-service:v1.0 -f user-service/deploy/Dockerfile ."
            }
        }
    }
    post {
        success {
            script {
                echo "构建成功"
                sh "docker run -d user-service:v1.0"
            }
        }

        failure {
            script {
                echo "构建失败"
            }
        }
    }
}