server:
  port: 8004
spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Lyt@2019
    url: jdbc:mysql://47.107.255.115:3306/hospital??useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://47.107.255.115:6006/eureka/

logging:
  level:
    com.sunchs.lyt.db.business.mapper: DEBUG
    com.sunchs.lyt.db.report.mapper: DEBUG
