server:
  port: 8004
spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Lyt@2019
    url: jdbc:mysql://47.107.255.115:3306/hospital??useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    druid:
      #初始化连接数
      initial-size: 1
      #最小空闲连接
      min-idle: 1
      #最大活动连接
      max-active: 10
      #获取连接时测试是否可用
      test-on-borrow: true
      #监控页面启动
      stat-view-servlet:
        allow: true

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://47.107.255.115:6006/eureka/

#logging:
#  level:
#    com.sunchs.lyt.db.business.mapper: DEBUG
#    com.sunchs.lyt.db.report.mapper: DEBUG
